// @ts-check

/**
 * @typedef {{ type: string, message: string }} AuditWarning
 * @typedef {{ name: string, id: string, score: number, reasons: string[] }} SimilarApp
 * @typedef {{
 *   id: string,
 *   name: string,
 *   relPath: string,
 *   description: string,
 *   frameworks: string[],
 *   languages: string[],
 *   zone: string,
 *   category: string,
 *   qualityScore: number,
 *   freshnessScore: number,
 *   docsScore: number,
 *   testingScore: number,
 *   readinessScore: number,
 *   daysOld: number,
 *   docsFiles: number,
 *   testFiles: number,
 *   sourceFiles: number,
 *   sourceLines: number,
 *   warnings?: AuditWarning[],
 *   scripts?: string[],
 *   similarApps?: SimilarApp[]
 * }} AuditProject
 * @typedef {{ zoneOptions: string[], categoryOptions: string[] }} AuditMeta
 * @typedef {{
 *   totalApps: number,
 *   avgQuality?: number,
 *   totalSource?: number,
 *   totalTests?: number,
 *   zoneCounts?: Record<string, number>,
 *   strongest?: { score: number, leftName: string, rightName: string }
 * }} AuditSummary
 * @typedef {{
 *   generatedAt?: string,
 *   rootDir?: string,
 *   meta: AuditMeta,
 *   summary: AuditSummary,
 *   crossChecks?: Array<{ leftId: string, rightId: string, leftName: string, rightName: string, score: number, reasons: string[] }>,
 *   projects: AuditProject[]
 * }} AuditPayload
 * @typedef {{
 *   id: string,
 *   projectId?: string,
 *   projectName?: string,
 *   severity: "high" | "medium" | "low",
 *   category: string,
 *   title: string,
 *   detail: string,
 *   createdAt: string,
 *   status: string
 * }} PersistedFinding
 * @typedef { "confirmed-overlap" | "not-related" | "needs-review" | "merge-candidate" } ConvergenceReviewStatus
 * @typedef {{
 *   id: string,
 *   pairId: string,
 *   leftId: string,
 *   rightId: string,
 *   leftName: string,
 *   rightName: string,
 *   score: number,
 *   reasons: string[],
 *   status: ConvergenceReviewStatus,
 *   note: string,
 *   reviewer: string,
 *   source: string,
 *   operatorContext?: string,
 *   generatedInsight?: string,
 *   assimilationRecommendation?: ConvergenceReviewStatus,
 *   createdAt: string,
 *   updatedAt: string,
 *   secretPolicy: string
 * }} ConvergenceReview
 * @typedef {{
 *   pairId: string,
 *   leftId: string,
 *   rightId: string,
 *   leftName: string,
 *   rightName: string,
 *   score: number,
 *   reasons: string[],
 *   reviewStatus: ConvergenceReviewStatus | "unreviewed",
 *   reviewId: string,
 *   reviewNote: string,
 *   reviewedAt: string,
 *   reviewer: string,
 *   reviewSource?: string,
 *   operatorProposed?: boolean,
 *   generatedInsight?: string,
 *   assimilationRecommendation?: ConvergenceReviewStatus,
 *   secretPolicy: string
 * }} ConvergenceCandidate
 * @typedef {{
 *   generatedAt: string,
 *   summary: {
 *     total: number,
 *     reviewed: number,
 *     unreviewed: number,
 *     confirmedOverlap: number,
 *     notRelated: number,
 *     needsReview: number,
 *     mergeCandidate: number
 *   },
 *   candidates: ConvergenceCandidate[],
 *   reviews: ConvergenceReview[],
 *   secretPolicy: string,
 *   markdown: string
 * }} ConvergenceCandidatesPayload
 * @typedef {{
 *   id: string,
 *   projectId?: string,
 *   projectName?: string,
 *   title: string,
 *   description?: string,
 *   priority: string,
 *   status: string,
 *   sourceAccessReviewId?: string,
 *   sourceAccessValidationEvidenceCoverageId?: string,
 *   sourceAccessValidationWorkflowId?: string,
 *   sourceId?: string,
 *   sourceLabel?: string,
 *   sourceType?: string,
 *   sourceValue?: string,
 *   accessMethod?: string,
 *   workflowStage?: string,
 *   workflowStatus?: string,
 *   blockerTypes?: string[],
 *   coverageStatus?: string,
 *   latestEvidenceStatus?: string,
 *   latestEvidenceId?: string,
 *   latestEvidenceAt?: string,
 *   lastSourceAccessValidationEvidenceId?: string,
 *   lastSourceAccessValidationEvidenceStatus?: string,
 *   lastSourceAccessValidationEvidenceAt?: string,
 *   releaseBuildGateActionId?: string,
 *   releaseBuildGateActionStatus?: string,
 *   releaseBuildGateActionPriority?: string,
 *   releaseBuildGateDecision?: string,
 *   releaseBuildGateRiskScore?: number,
 *   releaseBuildGateReasonCount?: number,
 *   releaseBuildGateCommandHint?: string,
 *   agentControlPlaneDecisionReasonCode?: string,
 *   agentControlPlaneDecisionReasonSeverity?: string,
 *   agentControlPlaneDecision?: string,
 *   agentControlPlaneRecommendedAction?: string,
 *   agentControlPlaneCommandHint?: string,
 *   agentExecutionResultCheckpointId?: string,
 *   agentExecutionResultRunId?: string,
 *   agentExecutionResultRunTitle?: string,
 *   agentExecutionResultRunStatus?: string,
 *   agentExecutionResultTargetAction?: AgentExecutionResultTargetAction,
 *   agentExecutionResultCheckpointStatus?: AgentExecutionResultCheckpointStatus,
 *   agentExecutionResultResultType?: string,
 *   secretPolicy?: string,
 *   createdAt: string,
 *   updatedAt: string
 * }} PersistedTask
 * @typedef {{
 *   id: string,
 *   projectId?: string,
 *   projectName?: string,
 *   title: string,
 *   brief?: string,
 *   status: string,
 *   phase: string,
 *   createdAt: string,
 *   updatedAt: string
 * }} PersistedWorkflow
 * @typedef {{
 *   id: string,
 *   projectId?: string,
 *   projectName?: string,
 *   relPath: string,
 *   script: string,
 *   status: "running" | "success" | "failed" | "cancelled",
 *   startedAt: string,
 *   endedAt?: string | null,
 *   exitCode?: number | null,
 *   detail?: string
 * }} PersistedScriptRun
 * @typedef {{
 *   id: string,
 *   projectId: string,
 *   projectName: string,
 *   relPath: string,
 *   title: string,
 *   summary?: string,
 *   handoffPack: string,
 *   status: string,
 *   createdAt: string,
 *   updatedAt: string
 * }} PersistedAgentSession
 * @typedef {{
 *   id: string,
 *   title: string,
 *   statusFilter: string,
 *   total: number,
 *   readyCount: number,
 *   needsPrepCount: number,
 *   blockedCount: number,
 *   approvedPolicyCount?: number,
 *   executableCount?: number,
 *   unresolvedPolicyCount?: number,
 *   markdown: string,
 *   items: GovernanceAgentReadinessItem[],
 *   createdAt: string
 * }} PersistedAgentWorkOrderSnapshot
 * @typedef {{
 *   id: string,
 *   status: string,
 *   previousStatus: string | null,
 *   note: string,
 *   actor: string,
 *   createdAt: string
 * }} PersistedAgentWorkOrderRunEvent
 * @typedef {{
 *   id: string,
 *   projectId: string,
 *   projectName: string,
 *   relPath: string,
 *   snapshotId: string,
 *   title: string,
 *   objective: string,
 *   status: "queued" | "running" | "blocked" | "passed" | "failed" | "cancelled",
 *   readinessScore: number,
 *   readinessStatus: string,
 *   blockers: string[],
 *   agentPolicyId?: string,
 *   agentPolicyCheckpointId?: string,
 *   agentPolicyCheckpointStatus?: "approved" | "deferred" | "dismissed" | "needs-review",
 *   agentRole?: string,
 *   runtime?: string,
 *   isolationMode?: string,
 *   skillBundle?: string[],
 *   hookPolicy?: string[],
 *   agentPolicySecretPolicy?: string,
 *   validationCommands: string[],
 *   notes: string,
 *   history: PersistedAgentWorkOrderRunEvent[],
 *   archivedAt: string,
 *   archivedBy: string,
 *   slaBreachedAt: string,
 *   slaResolvedAt: string,
 *   slaLastActionAt: string,
 *   slaAction: string,
 *   slaEscalationCount: number,
 *   slaResolutionCount: number,
 *   createdAt: string,
 *   updatedAt: string
 * }} PersistedAgentWorkOrderRun
 * @typedef {{
 *   id: string,
 *   sourceRunner: "codex" | "claude" | "operator" | "workspace-audit",
 *   targetRunner: "codex" | "claude" | "operator" | "workspace-audit",
 *   status: "proposed" | "accepted" | "rejected" | "needs-review",
 *   resultType: string,
 *   projectId: string,
 *   projectName: string,
 *   workOrderRunId: string,
 *   title: string,
 *   summary: string,
 *   changedFiles: string[],
 *   validationSummary: string,
 *   nextAction: string,
 *   notes: string,
 *   secretPolicy: string,
 *   createdAt: string,
 *   updatedAt: string
 * }} PersistedCliBridgeHandoff
 * @typedef {{
 *   generatedAt: string,
 *   runner: "all" | "codex" | "claude",
 *   limit: number,
 *   total: number,
 *   visible: number,
 *   secretPolicy: string,
 *   items: PersistedCliBridgeHandoff[],
 *   markdown: string
 * }} CliBridgeHandoffLedgerPayload
 * @typedef {{
 *   total: number,
 *   active: number,
 *   completed: number,
 *   archived: number,
 *   staleActive: number,
 *   slaBreached: number,
 *   slaResolved: number,
 *   slaAverageResolutionHours: number,
 *   completionRate: number,
 *   failureRate: number,
 *   statusCounts: {
 *     queued: number,
 *     running: number,
 *     blocked: number,
 *     passed: number,
 *     failed: number,
 *     cancelled: number,
 *     other: number
 *   },
 *   latestEventAt: string,
 *   latestEventNote: string,
 *   latestEventStatus: string,
 *   latestEventProjectName: string,
 *   latestEventRunTitle: string
 *   staleThresholdHours: number,
 *   staleStatuses: string[]
 * }} GovernanceAgentExecutionMetrics
 * @typedef {{
 *   staleThresholdHours: number,
 *   staleStatuses: string[],
 *   terminalStatuses: string[],
 *   updatedAt: string
 * }} GovernanceAgentExecutionPolicy
 * @typedef {{
 *   id: string,
 *   projectId?: string,
 *   projectName?: string,
 *   title: string,
 *   body?: string,
 *   kind: string,
 *   createdAt: string,
 *   updatedAt: string
 * }} PersistedNote
 * @typedef {{
 *   id: string,
 *   projectId?: string,
 *   projectName?: string,
 *   title: string,
 *   detail?: string,
 *   status: string,
 *   targetDate?: string,
 *   createdAt: string,
 *   updatedAt: string
 * }} PersistedMilestone
 * @typedef {{
 *   id: string,
 *   projectId: string,
 *   projectName: string,
 *   owner: string,
 *   status: string,
 *   lifecycle: string,
 *   tier: string,
 *   targetState: string,
 *   summary?: string,
 *   createdAt: string,
 *   updatedAt: string
 * }} PersistedProjectProfile
 * @typedef {{
 *   id: string,
 *   projectId: string,
 *   projectName: string,
 *   changeType: "created" | "updated",
 *   changedFields: string[],
 *   previous: {
 *     owner: string,
 *     status: string,
 *     lifecycle: string,
 *     tier: string,
 *     targetState: string,
 *     summary: string
 *   } | null,
 *   next: {
 *     owner: string,
 *     status: string,
 *     lifecycle: string,
 *     tier: string,
 *     targetState: string,
 *     summary: string
 *   },
 *   changedAt: string
 * }} PersistedProjectProfileHistory
 * @typedef {{
 *   id: string,
 *   name: string,
 *   relPath: string,
 *   zone: string,
 *   category: string,
 *   qualityScore: number,
 *   freshnessScore: number,
 *   docsFiles: number,
 *   testFiles: number,
 *   sourceFiles: number,
 *   sourceLines: number,
 *   daysOld: number,
 *   frameworks: string[],
 *   warningsCount: number
 * }} ProjectScanSnapshot
 * @typedef {{
 *   id: string,
 *   generatedAt: string,
 *   summary: AuditSummary,
 *   projects?: ProjectScanSnapshot[]
 * }} PersistedScanRun
 * @typedef {{
 *   id: string,
 *   name: string,
 *   relPath: string,
 *   zone: string,
 *   category: string,
 *   qualityDelta: number,
 *   freshnessDelta: number,
 *   sourceDelta: number,
 *   testDelta: number,
 *   docsDelta: number,
 *   lineDelta: number,
 *   warningsDelta: number,
 *   fromZone: string,
 *   toZone: string,
 *   fromCategory: string,
 *   toCategory: string,
 *   changeScore: number
 * }} ScanDiffProjectChange
 * @typedef {{
 *   status: "insufficient_data" | "summary_only" | "ready",
 *   latestGeneratedAt: string | null,
 *   previousGeneratedAt: string | null,
 *   totals: {
 *     appDelta: number,
 *     qualityDelta: number,
 *     sourceDelta: number,
 *     testDelta: number,
 *     addedCount: number,
 *     removedCount: number,
 *     changedCount: number
 *   },
 *   addedProjects: Array<Pick<ProjectScanSnapshot, "id" | "name" | "relPath" | "zone" | "category" | "qualityScore">>,
 *   removedProjects: Array<Pick<ProjectScanSnapshot, "id" | "name" | "relPath" | "zone" | "category" | "qualityScore">>,
 *   changedProjects: ScanDiffProjectChange[],
 *   topChanges: ScanDiffProjectChange[]
 * }} ScanDiffPayload
 * @typedef {{
 *   projectId?: string,
 *   kind: string,
 *   title: string,
 *   projectName: string,
 *   status: string,
 *   timestamp: string,
 *   detail: string
 * }} GovernanceActivity
 * @typedef {{
 *   id: string,
 *   name: string,
 *   relPath: string,
 *   zone: string,
 *   category: string,
 *   qualityScore: number,
 *   findingCount: number
 * }} GovernanceGapProject
 * @typedef {{
 *   id: string,
 *   projectId: string,
 *   projectName: string,
 *   kind: "profile-gap" | "owner-gap" | "task-gap" | "workflow-gap" | "decision-gap",
 *   title: string,
 *   detail: string,
 *   priority: "high" | "medium" | "low",
 *   actionType: "create-profile" | "create-task" | "create-workflow" | "create-starter-pack" | "create-decision-note" | "open-project",
 *   actionLabel: string
 * }} GovernanceQueueItem
 * @typedef {{
 *   id: string,
 *   projectId: string,
 *   projectName: string,
 *   kind: string,
 *   title: string,
 *   reason: string,
 *   suppressedAt: string
 * }} GovernanceQueueSuppression
 * @typedef {{
 *   id: string,
 *   type: string,
 *   summary: string,
 *   actor: string,
 *   details: Record<string, unknown>,
 *   createdAt: string
 * }} GovernanceOperation
 * @typedef {{
 *   id: string,
 *   batchId: string,
 *   title: string,
 *   source: string,
 *   status: "approved" | "deferred" | "dismissed" | "needs-review",
 *   itemCount: number,
 *   note: string,
 *   reviewer: string,
 *   secretPolicy: string,
 *   createdAt: string
 * }} TaskSeedingCheckpoint
 * @typedef { "approved" | "deferred" | "dismissed" | "needs-review" } AgentPolicyCheckpointStatus
 * @typedef {{
 *   total: number,
 *   approved: number,
 *   deferred: number,
 *   dismissed: number,
 *   needsReview: number,
 *   unresolved: number
 * }} AgentPolicyCheckpointSummary
 * @typedef {{
 *   id: string,
 *   policyId: string,
 *   projectId: string,
 *   projectName: string,
 *   relPath: string,
 *   status: AgentPolicyCheckpointStatus,
 *   role: string,
 *   runtime: string,
 *   isolationMode: string,
 *   skillBundle: string[],
 *   hookPolicy: string[],
 *   source: string,
 *   reason: string,
 *   note: string,
 *   reviewer: string,
 *   secretPolicy: string,
 *   createdAt: string
 * }} AgentPolicyCheckpoint
 * @typedef {{
 *   policyId: string,
 *   checkpointId: string,
 *   checkpointStatus: AgentPolicyCheckpointStatus,
 *   executable: boolean,
 *   role: string,
 *   runtime: string,
 *   isolationMode: string,
 *   skillBundle: string[],
 *   hookPolicy: string[],
 *   source: string,
 *   recommendedAction: string,
 *   secretPolicy: string
 * }} AgentPolicyRecommendation
 * @typedef {{
 *   generatedAt: string,
 *   summary: AgentPolicyCheckpointSummary,
 *   agentPolicyCheckpoints: AgentPolicyCheckpoint[],
 *   secretPolicy: string
 * }} AgentPolicyCheckpointsPayload
 * @typedef { AgentPolicyCheckpointStatus } AgentExecutionResultCheckpointStatus
 * @typedef { "retry" | "archive" | "retention" | "resolve-sla" | "baseline-refresh" } AgentExecutionResultTargetAction
 * @typedef {{
 *   total: number,
 *   approved: number,
 *   deferred: number,
 *   dismissed: number,
 *   needsReview: number,
 *   unresolved: number
 * }} AgentExecutionResultCheckpointSummary
 * @typedef {{
 *   runId: string,
 *   projectId: string,
 *   projectName: string,
 *   runTitle: string,
 *   runStatus: string,
 *   targetAction: AgentExecutionResultTargetAction,
 *   reason: string,
 *   checkpointStatus: AgentExecutionResultCheckpointStatus,
 *   checkpointId: string,
 *   updatedAt: string
 * }} AgentExecutionResultRequirementItem
 * @typedef {{
 *   retryBlocked: number,
 *   archiveBlocked: number,
 *   retentionBlocked: number,
 *   slaResolveBlocked: number,
 *   baselineBlocked: number,
 *   totalBlocked: number,
 *   items: AgentExecutionResultRequirementItem[]
 * }} AgentExecutionResultRequirements
 * @typedef {{
 *   id: string,
 *   runId: string,
 *   projectId: string,
 *   projectName: string,
 *   runTitle: string,
 *   runStatus: string,
 *   resultType: string,
 *   targetAction: AgentExecutionResultTargetAction,
 *   status: AgentExecutionResultCheckpointStatus,
 *   source: string,
 *   reason: string,
 *   note: string,
 *   reviewer: string,
 *   secretPolicy: string,
 *   createdAt: string
 * }} AgentExecutionResultCheckpoint
 * @typedef {{
 *   generatedAt: string,
 *   summary: AgentExecutionResultCheckpointSummary,
 *   requirements: AgentExecutionResultRequirements | null,
 *   agentExecutionResultCheckpoints: AgentExecutionResultCheckpoint[],
 *   secretPolicy: string
 * }} AgentExecutionResultCheckpointsPayload
 * @typedef {{
 *   operationId: string,
 *   type: string,
 *   summary: string,
 *   actor: string,
 *   taskId: string,
 *   title: string,
 *   projectId: string,
 *   projectName: string,
 *   previousStatus: string,
 *   nextStatus: string,
 *   updatedFields: string[],
 *   createdAt: string
 * }} GovernanceTaskUpdateLedgerItem
 * @typedef {{
 *   generatedAt: string,
 *   limit: number,
 *   secretPolicy: string,
 *   summary: {
 *     total: number,
 *     visible: number,
 *     statusChanges: number,
 *     metadataUpdates: number,
 *     taskCount: number,
 *     projectCount: number
 *   },
 *   items: GovernanceTaskUpdateLedgerItem[],
 *   markdown: string
 * }} GovernanceTaskUpdateLedgerPayload
 * @typedef {{
 *   id: string,
 *   title: string,
 *   limit: number,
 *   total: number,
 *   visibleCount: number,
 *   statusChangeCount: number,
 *   metadataUpdateCount: number,
 *   taskCount: number,
 *   projectCount: number,
 *   secretPolicy: string,
 *   markdown: string,
 *   items: GovernanceTaskUpdateLedgerItem[],
 *   createdAt: string
 * }} PersistedGovernanceTaskUpdateLedgerSnapshot
 * @typedef {{
 *   generatedAt: string,
 *   hasSnapshot: boolean,
 *   snapshotId: string,
 *   snapshotTitle: string,
 *   snapshotCreatedAt: string,
 *   hasDrift: boolean,
 *   driftScore: number,
 *   driftSeverity: "none" | "low" | "medium" | "high" | "missing-snapshot",
 *   recommendedAction: string,
 *   driftItems: Array<{ field: string, label: string, before: string | number, current: string | number, delta: number }>,
 *   liveSummary: GovernanceTaskUpdateLedgerPayload["summary"] | null,
 *   snapshotSummary: { total: number, visible: number, statusChanges: number, metadataUpdates: number, taskCount: number, projectCount: number } | null,
 *   markdown: string
 * }} GovernanceTaskUpdateLedgerSnapshotDiffPayload
 * @typedef {{
 *   id: string,
 *   title: string,
 *   search: string,
 *   scope: string,
 *   sort: string,
 *   taskSeedingStatus: string,
 *   executionStatus: string,
 *   executionRetention: number,
 *   showArchivedExecution: boolean,
 *   createdAt: string,
 *   updatedAt: string
 * }} PersistedGovernanceExecutionView
 * @typedef {{
 *   id: string,
 *   projectId: string,
 *   projectName: string,
 *   title: string,
 *   phase: string,
 *   status: string,
 *   readiness: string,
 *   priority: "high" | "medium" | "low",
 *   blockers: string[],
 *   nextStep: string,
 *   updatedAt: string
 * }} GovernanceWorkflowRunbookItem
 * @typedef {{
 *   projectId: string,
 *   projectName: string,
 *   relPath: string,
 *   status: "ready" | "needs-prep" | "blocked",
 *   score: number,
 *   owner: string,
 *   lifecycle: string,
 *   targetState: string,
 *   openFindingCount: number,
 *   openTaskCount: number,
 *   activeWorkflowCount: number,
 *   agentSessionCount: number,
 *   latestWorkflowTitle: string,
 *   latestAgentSessionAt: string,
 *   blockers: string[],
 *   nextStep: string,
 *   agentPolicy: AgentPolicyRecommendation,
 *   updatedAt: string
 * }} GovernanceAgentReadinessItem
 * @typedef {{
 *   id: string,
 *   projectId: string,
 *   projectName: string,
 *   title: string,
 *   status: string,
 *   breachState: string,
 *   action: string,
 *   breachedAt: string,
 *   resolvedAt: string,
 *   escalationCount: number,
 *   resolutionCount: number,
 *   durationHours: number,
 *   updatedAt: string
 * }} GovernanceAgentExecutionSlaLedgerItem
 * @typedef {{
 *   id: string,
 *   title: string,
 *   stateFilter: "all" | "open" | "resolved",
 *   limit: number,
 *   available: number,
 *   total: number,
 *   openCount: number,
 *   resolvedCount: number,
 *   markdown: string,
 *   items: GovernanceAgentExecutionSlaLedgerItem[],
 *   createdAt: string
 * }} PersistedAgentExecutionSlaLedgerSnapshot
 * @typedef {{
 *   id: string,
 *   title: string,
 *   limit: number,
 *   totalWorkOrders: number,
 *   totalExecutionRuns: number,
 *   totalExecutionResultCheckpoints: number,
 *   executionResultCheckpointRequiredCount: number,
 *   executionResultBaselineBlockedCount: number,
 *   executionResultCheckpoints: AgentExecutionResultCheckpoint[],
 *   executionResultRequirements: AgentExecutionResultRequirements | null,
 *   totalSlaLedgerRecords: number,
 *   totalSlaLedgerSnapshots: number,
 *   releaseBuildGateDecision: "ready" | "review" | "hold" | "not-evaluated",
 *   releaseBuildGateRiskScore: number,
 *   releaseBuildGateReasonCount: number,
 *   releaseBuildGateActionCount: number,
 *   releaseBuildGate: ReleaseBuildGatePayload | null,
 *   releaseControlTaskCount: number,
 *   releaseControlOpenTaskCount: number,
 *   releaseControlClosedTaskCount: number,
 *   releaseControlTasks: PersistedTask[],
 *   releaseTaskLedgerSnapshotCount: number,
 *   releaseTaskLedgerSnapshots: PersistedReleaseTaskLedgerSnapshot[],
 *   agentControlPlaneDecisionTaskCount: number,
 *   agentControlPlaneDecisionOpenTaskCount: number,
 *   agentControlPlaneDecisionClosedTaskCount: number,
 *   agentControlPlaneDecisionTasks: PersistedTask[],
 *   governanceTaskUpdateLedgerSnapshotCount: number,
 *   governanceTaskUpdateLedgerSnapshots: PersistedGovernanceTaskUpdateLedgerSnapshot[],
 *   agentControlPlaneDecisionTaskLedgerSnapshotCount: number,
 *   agentControlPlaneDecisionTaskLedgerSnapshots: PersistedAgentControlPlaneDecisionTaskLedgerSnapshot[],
 *   agentExecutionResultTaskLedgerSnapshotCount: number,
 *   agentExecutionResultTaskLedgerSnapshots: PersistedAgentExecutionResultTaskLedgerSnapshot[],
 *   dataSourcesGateDecision: "ready" | "review" | "hold" | "not-evaluated",
 *   dataSourcesReview: number,
 *   dataSourcesBlocked: number,
 *   dataSourcesAccessGate: DataSourcesAccessGatePayload | null,
 *   dataSourcesAccessReviewQueueCount: number,
 *   dataSourcesAccessReviewQueue: DataSourcesAccessReviewQueuePayload | null,
 *   dataSourcesAccessValidationMethodCount: number,
 *   dataSourcesAccessValidationSourceCount: number,
 *   dataSourcesAccessValidationRunbook: DataSourcesAccessValidationRunbookPayload | null,
 *   dataSourcesAccessValidationWorkflowTotalCount: number,
 *   dataSourcesAccessValidationWorkflowReadyCount: number,
 *   dataSourcesAccessValidationWorkflowPendingCount: number,
 *   dataSourcesAccessValidationWorkflowBlockedCount: number,
 *   dataSourcesAccessValidationWorkflowMissingEvidenceCount: number,
 *   dataSourcesAccessValidationWorkflow: DataSourcesAccessValidationWorkflowPayload | null,
 *   dataSourceAccessValidationWorkflowSnapshotCount: number,
 *   dataSourceAccessValidationWorkflowSnapshotHasDrift: boolean,
 *   dataSourceAccessValidationWorkflowSnapshotDriftScore: number,
 *   dataSourceAccessValidationWorkflowSnapshotDriftSeverity: "none" | "low" | "medium" | "high" | "missing-snapshot",
 *   dataSourceAccessValidationWorkflowSnapshots: PersistedDataSourcesAccessValidationWorkflowSnapshot[],
 *   dataSourceAccessValidationWorkflowSnapshotDiff: DataSourcesAccessValidationWorkflowSnapshotDiffPayload | null,
 *   dataSourcesAccessValidationEvidenceCount: number,
 *   dataSourcesAccessValidationEvidenceValidatedCount: number,
 *   dataSourcesAccessValidationEvidenceCoverageCount: number,
 *   dataSourcesAccessValidationEvidenceCoverageCoveredCount: number,
 *   dataSourcesAccessValidationEvidenceCoverageMissingCount: number,
 *   dataSourcesAccessValidationEvidenceCoverageHighPriorityCount: number,
 *   dataSourcesAccessValidationEvidenceCoveragePercent: number,
 *   dataSourcesAccessValidationEvidenceCoverage: DataSourcesAccessValidationEvidenceCoveragePayload | null,
 *   sourceAccessCheckpointCount: number,
 *   sourceAccessCheckpointApprovedCount: number,
 *   sourceAccessCheckpointDeferredCount: number,
 *   sourceAccessCheckpointDismissedCount: number,
 *   sourceAccessCheckpointNeedsReviewCount: number,
 *   sourceAccessCheckpointUnresolvedCount: number,
 *   sourceAccessCheckpointSources: number,
 *   sourceAccessCheckpointBySource: Array<{ source: string, total: number, approved: number, deferred: number, dismissed: number, needsReview: number, unresolved: number, latestAt: string }>,
 *   dataSourceAccessValidationEvidenceSnapshotCount: number,
 *   dataSourceAccessValidationEvidence: DataSourcesAccessValidationEvidenceRecord[],
 *   dataSourceAccessValidationEvidenceSnapshots: PersistedDataSourcesAccessValidationEvidenceSnapshot[],
 *   summary: Record<string, unknown>,
 *   markdown: string,
 *   payload: Record<string, unknown>,
 *   createdAt: string,
 *   isBaseline?: boolean
 * }} PersistedAgentControlPlaneSnapshot
 * @typedef {{
 *   id: string,
 *   title: string,
 *   decision: "ready" | "review" | "hold",
 *   recommendedAction: string,
 *   reasonCount: number,
 *   reasonCodes: string[],
 *   reasons: AgentControlPlaneDecisionReason[],
 *   baselineHealth: "missing" | "healthy" | "changed" | "drifted" | "stale",
 *   baselineDriftSeverity: "none" | "low" | "medium" | "high" | "missing-baseline",
 *   activeRuns: number,
 *   staleActiveRuns: number,
 *   slaBreachedRuns: number,
 *   agentReadyProjects: number,
 *   agentReadinessItems: number,
 *   agentPolicyCheckpointCount: number,
 *   agentPolicyCheckpointApprovedCount: number,
 *   agentPolicyCheckpointDeferredCount: number,
 *   agentPolicyCheckpointDismissedCount: number,
 *   agentPolicyCheckpointNeedsReviewCount: number,
 *   agentPolicyCheckpointUnresolvedCount: number,
 *   agentPolicyExecutableCount: number,
 *   agentExecutionResultCheckpointCount: number,
 *   agentExecutionResultCheckpointApprovedCount: number,
 *   agentExecutionResultCheckpointDeferredCount: number,
 *   agentExecutionResultCheckpointDismissedCount: number,
 *   agentExecutionResultCheckpointNeedsReviewCount: number,
 *   agentExecutionResultCheckpointUnresolvedCount: number,
 *   agentExecutionResultCheckpointRequiredCount: number,
 *   agentExecutionResultBaselineBlockedCount: number,
 *   agentExecutionResultRequirements: AgentExecutionResultRequirements | null,
 *   releaseBuildGateDecision: "ready" | "review" | "hold" | "not-evaluated",
 *   releaseBuildGateRiskScore: number,
 *   releaseBuildGateReasonCount: number,
 *   releaseBuildGateActionCount: number,
 *   releaseBuildGate: ReleaseBuildGatePayload | null,
 *   releaseControlTaskCount: number,
 *   releaseControlOpenTaskCount: number,
 *   releaseControlClosedTaskCount: number,
 *   releaseControlTasks: PersistedTask[],
 *   releaseTaskLedgerSnapshotCount: number,
 *   releaseTaskLedgerSnapshots: PersistedReleaseTaskLedgerSnapshot[],
 *   agentControlPlaneDecisionTaskCount: number,
 *   agentControlPlaneDecisionOpenTaskCount: number,
 *   agentControlPlaneDecisionClosedTaskCount: number,
 *   agentControlPlaneDecisionTasks: PersistedTask[],
 *   agentExecutionResultTaskCount: number,
 *   agentExecutionResultOpenTaskCount: number,
 *   agentExecutionResultClosedTaskCount: number,
 *   agentExecutionResultTasks: PersistedTask[],
 *   dataSourcesGateDecision: "ready" | "review" | "hold" | "not-evaluated",
 *   dataSourcesReview: number,
 *   dataSourcesBlocked: number,
 *   dataSourcesAccessGate: DataSourcesAccessGatePayload | null,
 *   dataSourcesAccessReviewQueueCount: number,
 *   dataSourcesAccessReviewQueue: DataSourcesAccessReviewQueuePayload | null,
 *   dataSourcesAccessValidationMethodCount: number,
 *   dataSourcesAccessValidationSourceCount: number,
 *   dataSourcesAccessValidationReviewCount: number,
 *   dataSourcesAccessValidationBlockedCount: number,
 *   dataSourcesAccessValidationRunbook: DataSourcesAccessValidationRunbookPayload | null,
 *   dataSourcesAccessValidationWorkflowTotalCount: number,
 *   dataSourcesAccessValidationWorkflowReadyCount: number,
 *   dataSourcesAccessValidationWorkflowPendingCount: number,
 *   dataSourcesAccessValidationWorkflowBlockedCount: number,
 *   dataSourcesAccessValidationWorkflowMissingEvidenceCount: number,
 *   dataSourcesAccessValidationWorkflow: DataSourcesAccessValidationWorkflowPayload | null,
 *   dataSourceAccessValidationWorkflowSnapshotCount: number,
 *   dataSourceAccessValidationWorkflowSnapshotHasDrift: boolean,
 *   dataSourceAccessValidationWorkflowSnapshotDriftScore: number,
 *   dataSourceAccessValidationWorkflowSnapshotDriftSeverity: "none" | "low" | "medium" | "high" | "missing-snapshot",
 *   dataSourceAccessValidationWorkflowSnapshots: PersistedDataSourcesAccessValidationWorkflowSnapshot[],
 *   dataSourceAccessValidationWorkflowSnapshotDiff: DataSourcesAccessValidationWorkflowSnapshotDiffPayload | null,
 *   dataSourcesAccessValidationEvidenceCount: number,
 *   dataSourcesAccessValidationEvidenceValidatedCount: number,
 *   dataSourcesAccessValidationEvidenceReviewCount: number,
 *   dataSourcesAccessValidationEvidenceBlockedCount: number,
 *   dataSourcesAccessValidationEvidenceCoverageCount: number,
 *   dataSourcesAccessValidationEvidenceCoverageCoveredCount: number,
 *   dataSourcesAccessValidationEvidenceCoverageReviewCount: number,
 *   dataSourcesAccessValidationEvidenceCoverageBlockedCount: number,
 *   dataSourcesAccessValidationEvidenceCoverageMissingCount: number,
 *   dataSourcesAccessValidationEvidenceCoverageHighPriorityCount: number,
 *   dataSourcesAccessValidationEvidenceCoveragePercent: number,
 *   dataSourcesAccessValidationEvidenceCoverage: DataSourcesAccessValidationEvidenceCoveragePayload | null,
 *   sourceAccessCheckpointCount: number,
 *   sourceAccessCheckpointApprovedCount: number,
 *   sourceAccessCheckpointDeferredCount: number,
 *   sourceAccessCheckpointDismissedCount: number,
 *   sourceAccessCheckpointNeedsReviewCount: number,
 *   sourceAccessCheckpointUnresolvedCount: number,
 *   sourceAccessCheckpointSources: number,
 *   sourceAccessCheckpointBySource: Array<{ source: string, total: number, approved: number, deferred: number, dismissed: number, needsReview: number, unresolved: number, latestAt: string }>,
 *   dataSourceAccessValidationEvidenceSnapshotCount: number,
 *   dataSourceAccessValidationEvidence: DataSourcesAccessValidationEvidenceRecord[],
 *   dataSourcesAccessTaskCount: number,
 *   dataSourcesAccessOpenTaskCount: number,
 *   dataSourcesAccessClosedTaskCount: number,
 *   dataSourcesAccessTasks: PersistedTask[],
 *   markdown: string,
 *   payload: AgentControlPlaneDecisionPayload,
 *   createdAt: string
 * }} PersistedAgentControlPlaneDecisionSnapshot
 * @typedef {{
 *   summary: {
 *     openFindings: number,
 *     openTasks: number,
 *     activeWorkflows: number,
 *     pendingMilestones: number,
 *     decisionNotes: number,
 *     trackedProjects: number,
 *     profileCount: number,
 *     ownedProfiles: number,
 *     actionQueueItems: number,
 *     suppressedQueueItems: number,
 *     governanceOperationCount: number,
 *     taskSeedingCheckpointCount: number,
 *     agentPolicyCheckpointCount: number,
 *     agentPolicyCheckpointApprovedCount: number,
 *     agentPolicyCheckpointDeferredCount: number,
 *     agentPolicyCheckpointDismissedCount: number,
 *     agentPolicyCheckpointNeedsReviewCount: number,
 *     agentPolicyCheckpointUnresolvedCount: number,
 *     agentPolicyExecutableCount: number,
 *     agentExecutionResultCheckpointCount: number,
 *     agentExecutionResultCheckpointApprovedCount: number,
 *     agentExecutionResultCheckpointDeferredCount: number,
 *     agentExecutionResultCheckpointDismissedCount: number,
 *     agentExecutionResultCheckpointNeedsReviewCount: number,
 *     agentExecutionResultCheckpointUnresolvedCount: number,
 *     agentExecutionResultRetryBlockedCount: number,
 *     agentExecutionResultArchiveBlockedCount: number,
 *     agentExecutionResultRetentionBlockedCount: number,
 *     agentExecutionResultSlaResolveBlockedCount: number,
 *     agentExecutionResultBaselineBlockedCount: number,
 *     agentExecutionResultCheckpointRequiredCount: number,
 *     agentExecutionResultTaskCount: number,
 *     agentExecutionResultOpenTaskCount: number,
 *     agentExecutionResultClosedTaskCount: number,
 *     sourceAccessCheckpointCount: number,
 *     sourceAccessCheckpointApprovedCount: number,
 *     sourceAccessCheckpointDeferredCount: number,
 *     sourceAccessCheckpointDismissedCount: number,
 *     sourceAccessCheckpointNeedsReviewCount: number,
 *     sourceAccessCheckpointUnresolvedCount: number,
 *     sourceAccessCheckpointSources: number,
 *     sourceAccessCheckpointBySource: Array<{ source: string, total: number, approved: number, deferred: number, dismissed: number, needsReview: number, unresolved: number, latestAt: string }>,
 *     workflowRunbookItems: number,
 *     agentSessionCount: number,
 *     agentControlPlaneSnapshotCount: number,
 *     agentControlPlaneDecisionSnapshotCount: number,
 *     agentControlPlaneBaselineSnapshotId: string,
 *     agentControlPlaneBaselineSnapshotTitle: string,
 *     agentControlPlaneBaselineSnapshotCreatedAt: string,
 *     agentControlPlaneBaselineAgeHours: number,
 *     agentControlPlaneBaselineFreshness: string,
 *     agentControlPlaneBaselineFreshnessThresholdHours: number,
 *     agentControlPlaneBaselineHasDrift: boolean,
 *     agentControlPlaneBaselineDriftScore: number,
 *     agentControlPlaneBaselineDriftItems: Array<{ field: string, label: string, before: number, current: number, delta: number }>,
 *     agentControlPlaneBaselineDriftSeverity: "none" | "low" | "medium" | "high" | "missing-baseline",
 *     agentControlPlaneBaselineDriftRecommendedAction: string,
 *     agentControlPlaneBaselineHealth: "missing" | "healthy" | "changed" | "drifted" | "stale",
 *     agentControlPlaneBaselineRecommendedAction: string,
 *     agentWorkOrderSnapshotCount: number,
 *     agentExecutionSlaLedgerSnapshotCount: number,
 *     agentWorkOrderRunCount: number,
 *     cliBridgeHandoffCount: number,
 *     governanceExecutionViewCount: number,
 *     archivedAgentWorkOrderRunCount: number,
 *     activeAgentWorkOrderRunCount: number,
 *     blockedAgentWorkOrderRunCount: number,
 *     staleAgentWorkOrderRunCount: number,
 *     slaBreachedAgentWorkOrderRunCount: number,
 *     agentExecutionSlaLedgerCount: number,
 *     dataSourcesAccessGateDecision: "ready" | "review" | "hold" | "not-evaluated",
 *     dataSourcesAccessGateRank: number,
 *     dataSourcesAccessReadyCount: number,
 *     dataSourcesAccessReviewCount: number,
 *     dataSourcesAccessBlockedCount: number,
 *     dataSourcesAccessTokenLikelyCount: number,
 *     dataSourcesAccessReviewQueueCount: number,
 *     dataSourcesAccessReviewBlockedCount: number,
 *     dataSourcesAccessReviewHighCount: number,
 *     dataSourcesAccessReviewMediumCount: number,
 *     dataSourcesAccessValidationMethodCount: number,
 *     dataSourcesAccessValidationSourceCount: number,
 *     dataSourcesAccessValidationReviewCount: number,
 *     dataSourcesAccessValidationBlockedCount: number,
 *     dataSourcesAccessValidationWorkflowTotalCount: number,
 *     dataSourcesAccessValidationWorkflowReadyCount: number,
 *     dataSourcesAccessValidationWorkflowPendingCount: number,
 *     dataSourcesAccessValidationWorkflowBlockedCount: number,
 *     dataSourcesAccessValidationWorkflowMissingEvidenceCount: number,
 *     dataSourcesAccessValidationEvidenceCount: number,
 *     dataSourcesAccessValidationEvidenceValidatedCount: number,
 *     dataSourcesAccessValidationEvidenceReviewCount: number,
 *     dataSourcesAccessValidationEvidenceBlockedCount: number,
 *     dataSourcesAccessValidationEvidenceCoverageCount: number,
 *     dataSourcesAccessValidationEvidenceCoverageCoveredCount: number,
 *     dataSourcesAccessValidationEvidenceCoverageReviewCount: number,
 *     dataSourcesAccessValidationEvidenceCoverageBlockedCount: number,
 *     dataSourcesAccessValidationEvidenceCoverageMissingCount: number,
 *     dataSourcesAccessValidationEvidenceCoverageHighPriorityCount: number,
 *     dataSourcesAccessValidationEvidenceCoveragePercent: number,
 *     dataSourceAccessValidationEvidenceSnapshotCount: number,
 *     dataSourceAccessValidationEvidenceSnapshotHasDrift: boolean,
 *     dataSourceAccessValidationEvidenceSnapshotDriftScore: number,
 *     dataSourceAccessValidationEvidenceSnapshotDriftSeverity: "none" | "low" | "medium" | "high" | "missing-snapshot",
 *     dataSourceAccessValidationWorkflowSnapshotCount: number,
 *     dataSourceAccessValidationWorkflowSnapshotHasDrift: boolean,
 *     dataSourceAccessValidationWorkflowSnapshotDriftScore: number,
 *     dataSourceAccessValidationWorkflowSnapshotDriftSeverity: "none" | "low" | "medium" | "high" | "missing-snapshot",
 *     dataSourcesAccessTaskCount: number,
 *     dataSourcesAccessOpenTaskCount: number,
 *     dataSourcesAccessClosedTaskCount: number,
 *     dataSourceAccessTaskLedgerSnapshotCount: number,
 *     governanceTaskUpdateLedgerSnapshotCount: number,
 *     agentControlPlaneDecisionTaskLedgerSnapshotCount: number,
 *     agentExecutionResultTaskLedgerSnapshotCount: number,
 *     deploymentSmokeCheckCount: number,
 *     deploymentSmokeCheckPassCount: number,
 *     deploymentSmokeCheckFailCount: number,
 *     releaseCheckpointCount: number,
 *     releaseLatestCheckpointStatus: string,
 *     releaseLatestCheckpointAt: string,
 *     releaseLatestCheckpointTitle: string,
 *     releaseBuildGateDecision: "ready" | "review" | "hold" | "not-evaluated",
 *     releaseBuildGateRank: number,
 *     releaseBuildGateRiskScore: number,
 *     releaseBuildGateReasonCount: number,
 *     releaseBuildGateActionCount: number,
 *     releaseControlTaskCount: number,
 *     releaseControlOpenTaskCount: number,
 *     releaseControlClosedTaskCount: number,
 *     releaseTaskLedgerSnapshotCount: number,
 *     agentReadyProjects: number,
 *     agentReadinessItems: number
 *   },
 *   recentActivity: GovernanceActivity[],
 *   workflowFocus: PersistedWorkflow[],
  *   milestoneFocus: PersistedMilestone[],
  *   decisions: PersistedNote[],
  *   profiles: PersistedProjectProfile[],
 *   profileHistory: PersistedProjectProfileHistory[],
 *   actionQueue: GovernanceQueueItem[],
  *   queueSuppressions: GovernanceQueueSuppression[],
 *   operationLog: GovernanceOperation[],
 *   taskSeedingCheckpoints: TaskSeedingCheckpoint[],
 *   governanceTaskUpdateLedger?: GovernanceTaskUpdateLedgerPayload | null,
 *   governanceTaskUpdateLedgerSnapshotDiff?: GovernanceTaskUpdateLedgerSnapshotDiffPayload | null,
 *   agentPolicyCheckpoints: AgentPolicyCheckpoint[],
 *   agentExecutionResultCheckpoints: AgentExecutionResultCheckpoint[],
 *   agentExecutionResultRequirements: AgentExecutionResultRequirements,
 *   agentExecutionResultTasks: PersistedTask[],
 *   workflowRunbook: GovernanceWorkflowRunbookItem[],
 *   agentSessions: PersistedAgentSession[],
 *   agentControlPlaneBaselineStatus: GovernanceAgentControlPlaneBaselineStatus | null,
 *   agentControlPlaneDecision: AgentControlPlaneDecisionPayload,
 *   agentControlPlaneSnapshots: PersistedAgentControlPlaneSnapshot[],
 *   agentControlPlaneBaselineSnapshotId: string,
 *   agentControlPlaneDecisionSnapshots: PersistedAgentControlPlaneDecisionSnapshot[],
 *   governanceTaskUpdateLedgerSnapshots: PersistedGovernanceTaskUpdateLedgerSnapshot[],
 *   agentControlPlaneDecisionTaskLedgerSnapshots: PersistedAgentControlPlaneDecisionTaskLedgerSnapshot[],
 *   agentControlPlaneDecisionTaskLedgerSnapshotDiff?: AgentControlPlaneDecisionTaskLedgerSnapshotDiffPayload | null,
 *   agentExecutionResultTaskLedgerSnapshots: PersistedAgentExecutionResultTaskLedgerSnapshot[],
 *   agentExecutionResultTaskLedgerSnapshotDiff?: AgentExecutionResultTaskLedgerSnapshotDiffPayload | null,
 *   agentWorkOrderSnapshots: PersistedAgentWorkOrderSnapshot[],
 *   dataSourceAccessTaskLedgerSnapshots: PersistedDataSourcesAccessTaskLedgerSnapshot[],
 *   dataSourceAccessTaskLedgerSnapshotDiff?: DataSourcesAccessTaskLedgerSnapshotDiffPayload | null,
 *   agentExecutionSlaLedgerSnapshots: PersistedAgentExecutionSlaLedgerSnapshot[],
 *   agentWorkOrderRuns: PersistedAgentWorkOrderRun[],
 *   cliBridgeHandoffs: PersistedCliBridgeHandoff[],
 *   agentExecutionSlaLedger: GovernanceAgentExecutionSlaLedgerItem[],
 *   agentExecutionMetrics: GovernanceAgentExecutionMetrics,
 *   agentExecutionPolicy: GovernanceAgentExecutionPolicy,
 *   deploymentSmokeChecks?: DeploymentSmokeCheckRecord[],
 *   releaseCheckpoints?: ReleaseCheckpointRecord[],
 *   releaseSummary?: ReleaseSummaryPayload | null,
 *   releaseCheckpointDrift?: ReleaseCheckpointDriftPayload | null,
 *   releaseBuildGate?: ReleaseBuildGatePayload | null,
 *   releaseControlTasks: PersistedTask[],
 *   releaseTaskLedgerSnapshots: PersistedReleaseTaskLedgerSnapshot[],
 *   releaseTaskLedgerSnapshotDiff?: ReleaseTaskLedgerSnapshotDiffPayload | null,
 *   agentControlPlaneDecisionTasks: PersistedTask[],
 *   dataSourcesAccessGate: DataSourcesAccessGatePayload | null,
 *   dataSourcesAccessReviewQueue: DataSourcesAccessReviewQueuePayload | null,
 *   dataSourcesAccessValidationRunbook: DataSourcesAccessValidationRunbookPayload | null,
 *   dataSourcesAccessValidationWorkflow: DataSourcesAccessValidationWorkflowPayload | null,
 *   dataSourcesAccessValidationEvidenceCoverage: DataSourcesAccessValidationEvidenceCoveragePayload | null,
 *   dataSourceAccessValidationEvidence: DataSourcesAccessValidationEvidenceRecord[],
 *   dataSourceAccessValidationEvidenceSnapshots: PersistedDataSourcesAccessValidationEvidenceSnapshot[],
 *   dataSourceAccessValidationEvidenceSnapshotDiff: DataSourcesAccessValidationEvidenceSnapshotDiffPayload,
 *   dataSourceAccessValidationWorkflowSnapshots: PersistedDataSourcesAccessValidationWorkflowSnapshot[],
 *   dataSourceAccessValidationWorkflowSnapshotDiff: DataSourcesAccessValidationWorkflowSnapshotDiffPayload,
 *   dataSourcesAccessTasks: PersistedTask[],
 *   agentReadinessMatrix: GovernanceAgentReadinessItem[],
  *   unprofiledProjects: GovernanceGapProject[]
 * }} GovernancePayload
 * @typedef {{
 *   generatedAt: string,
 *   status: string,
 *   total: number,
 *   items: GovernanceAgentReadinessItem[],
 *   markdown: string
 * }} AgentWorkOrdersPayload
 * @typedef {{
 *   generatedAt: string,
 *   state: "all" | "open" | "resolved",
 *   limit: number,
 *   available: number,
 *   total: number,
 *   items: GovernanceAgentExecutionSlaLedgerItem[],
 *   markdown: string
 * }} AgentExecutionSlaLedgerPayload
 * @typedef {{
 *   generatedAt: string,
 *   limit: number,
 *   summary: GovernancePayload["summary"],
 *   agentExecutionMetrics: GovernanceAgentExecutionMetrics,
 *   agentExecutionPolicy: GovernanceAgentExecutionPolicy,
 *   baselineStatus: GovernanceAgentControlPlaneBaselineStatus | null,
 *   releaseBuildGate: ReleaseBuildGatePayload | null,
 *   releaseControlTasks: PersistedTask[],
 *   releaseTaskLedgerSnapshots: PersistedReleaseTaskLedgerSnapshot[],
 *   agentControlPlaneDecisionTasks: PersistedTask[],
 *   governanceTaskUpdateLedgerSnapshots: PersistedGovernanceTaskUpdateLedgerSnapshot[],
 *   agentControlPlaneDecisionTaskLedgerSnapshots: PersistedAgentControlPlaneDecisionTaskLedgerSnapshot[],
 *   agentExecutionResultTaskLedgerSnapshots: PersistedAgentExecutionResultTaskLedgerSnapshot[],
 *   agentControlPlaneDecisionTaskLedgerSnapshotDiff?: AgentControlPlaneDecisionTaskLedgerSnapshotDiffPayload | null,
 *   dataSourcesAccessGate: DataSourcesAccessGatePayload | null,
 *   dataSourcesAccessReviewQueue: DataSourcesAccessReviewQueuePayload | null,
 *   dataSourcesAccessValidationRunbook: DataSourcesAccessValidationRunbookPayload | null,
 *   dataSourcesAccessValidationWorkflow: DataSourcesAccessValidationWorkflowPayload | null,
 *   dataSourcesAccessValidationEvidenceCoverage: DataSourcesAccessValidationEvidenceCoveragePayload | null,
 *   dataSourceAccessValidationEvidence: DataSourcesAccessValidationEvidenceRecord[],
 *   dataSourceAccessValidationEvidenceSnapshots: PersistedDataSourcesAccessValidationEvidenceSnapshot[],
 *   dataSourceAccessValidationWorkflowSnapshots: PersistedDataSourcesAccessValidationWorkflowSnapshot[],
 *   dataSourceAccessValidationWorkflowSnapshotDiff: DataSourcesAccessValidationWorkflowSnapshotDiffPayload | null,
 *   readiness: GovernanceAgentReadinessItem[],
 *   agentSessions: PersistedAgentSession[],
 *   workOrders: AgentWorkOrdersPayload,
 *   executionRuns: PersistedAgentWorkOrderRun[],
 *   executionResultCheckpoints: AgentExecutionResultCheckpoint[],
 *   executionResultRequirements: AgentExecutionResultRequirements | null,
 *   slaLedger: AgentExecutionSlaLedgerPayload,
 *   workOrderSnapshots: PersistedAgentWorkOrderSnapshot[],
 *   decisionSnapshots: PersistedAgentControlPlaneDecisionSnapshot[],
 *   slaLedgerSnapshots: PersistedAgentExecutionSlaLedgerSnapshot[],
 *   markdown: string
 * }} AgentControlPlanePayload
 * @typedef {{
 *   id: "codex" | "claude",
 *   label: string,
 *   method: string,
 *   purpose: string,
 *   commandPattern: string,
 *   outputExpectation: string,
 *   executionPolicy: string
 * }} CliBridgeAdapter
 * @typedef {{
 *   generatedAt: string,
 *   protocolVersion: string,
 *   bridgeMode: string,
 *   executionMode: "non-executing",
 *   runner: "all" | "codex" | "claude",
 *   status: string,
 *   limit: number,
 *   bridgeDecision: "ready" | "review" | "hold",
 *   recommendedAction: string,
 *   secretPolicy: string,
 *   reasons: AgentControlPlaneDecisionReason[],
 *   adapters: CliBridgeAdapter[],
 *   workOrders: AgentWorkOrdersPayload,
 *   executableWorkOrderCount: number,
 *   controlPlaneDecision: {
 *     decision: "ready" | "review" | "hold",
 *     recommendedAction: string,
 *     reasonCount: number,
 *     baselineHealth: string,
 *     baselineDriftSeverity: string,
 *     releaseBuildGateDecision: string,
 *     dataSourcesGateDecision: string,
 *     activeRuns: number,
 *     staleActiveRuns: number,
 *     slaBreachedRuns: number
 *   },
 *   handoffContract: {
 *     input: string[],
 *     output: string[],
 *     prohibited: string[]
 *   },
 *   validationLoop: string[],
 *   markdown: string
 * }} CliBridgeContextPayload
 * @typedef {{
 *   severity: "review" | "hold",
 *   code: string,
 *   message: string
 * }} AgentControlPlaneDecisionReason
 * @typedef {{
 *   id: string,
 *   title: string,
 *   status: string,
 *   priority: string,
 *   projectId: string,
 *   projectName: string,
 *   agentControlPlaneDecisionReasonCode: string,
 *   agentControlPlaneDecisionReasonSeverity: string,
 *   agentControlPlaneDecision: string,
 *   agentControlPlaneRecommendedAction: string,
 *   agentControlPlaneCommandHint: string,
 *   description: string,
 *   secretPolicy: string,
 *   createdAt: string,
 *   updatedAt: string
 * }} AgentControlPlaneDecisionTaskLedgerItem
 * @typedef {{
 *   generatedAt: string,
 *   status: "all" | "open" | "closed",
 *   limit: number,
 *   secretPolicy: string,
 *   summary: {
 *     total: number,
 *     open: number,
 *     closed: number,
 *     visible: number,
 *     high: number,
 *     medium: number,
 *     low: number,
 *     normal: number,
 *     reasonCount: number,
 *     decisionCounts: Record<string, number>
 *   },
 *   items: AgentControlPlaneDecisionTaskLedgerItem[],
 *   markdown: string
 * }} AgentControlPlaneDecisionTaskLedgerPayload
 * @typedef {{
 *   id: string,
 *   title: string,
 *   statusFilter: "all" | "open" | "closed",
 *   limit: number,
 *   total: number,
 *   openCount: number,
 *   closedCount: number,
 *   visibleCount: number,
 *   reasonCount: number,
 *   secretPolicy: string,
 *   markdown: string,
 *   items: AgentControlPlaneDecisionTaskLedgerItem[],
 *   createdAt: string
 * }} PersistedAgentControlPlaneDecisionTaskLedgerSnapshot
 * @typedef {{
 *   generatedAt: string,
 *   hasSnapshot: boolean,
 *   snapshotId: string,
 *   snapshotTitle: string,
 *   snapshotCreatedAt: string,
 *   hasDrift: boolean,
 *   driftScore: number,
 *   driftSeverity: "none" | "low" | "medium" | "high" | "missing-snapshot",
 *   recommendedAction: string,
 *   driftItems: Array<{ field: string, label: string, before: string | number, current: string | number, delta: number }>,
 *   liveSummary: AgentControlPlaneDecisionTaskLedgerPayload["summary"] | null,
 *   snapshotSummary: { total: number, open: number, closed: number, visible: number, reasonCount: number } | null,
 *   markdown: string
 * }} AgentControlPlaneDecisionTaskLedgerSnapshotDiffPayload
 * @typedef {{
 *   id: string,
 *   title: string,
 *   status: string,
 *   priority: string,
 *   projectId: string,
 *   projectName: string,
 *   agentExecutionResultCheckpointId: string,
 *   agentExecutionResultRunId: string,
 *   agentExecutionResultRunTitle: string,
 *   agentExecutionResultRunStatus: string,
 *   agentExecutionResultTargetAction: string,
 *   agentExecutionResultCheckpointStatus: string,
 *   agentExecutionResultResultType: string,
 *   description: string,
 *   secretPolicy: string,
 *   createdAt: string,
 *   updatedAt: string
 * }} AgentExecutionResultTaskLedgerItem
 * @typedef {{
 *   generatedAt: string,
 *   status: "all" | "open" | "closed",
 *   limit: number,
 *   secretPolicy: string,
 *   summary: {
 *     total: number,
 *     open: number,
 *     closed: number,
 *     visible: number,
 *     high: number,
 *     medium: number,
 *     low: number,
 *     normal: number,
 *     actionCount: number,
 *     actionCounts: Record<string, number>
 *   },
 *   items: AgentExecutionResultTaskLedgerItem[],
 *   markdown: string
 * }} AgentExecutionResultTaskLedgerPayload
 * @typedef {{
 *   id: string,
 *   title: string,
 *   statusFilter: "all" | "open" | "closed",
 *   limit: number,
 *   total: number,
 *   openCount: number,
 *   closedCount: number,
 *   visibleCount: number,
 *   actionCount: number,
 *   secretPolicy: string,
 *   markdown: string,
 *   items: AgentExecutionResultTaskLedgerItem[],
 *   createdAt: string
 * }} PersistedAgentExecutionResultTaskLedgerSnapshot
 * @typedef {{
 *   generatedAt: string,
 *   hasSnapshot: boolean,
 *   snapshotId: string,
 *   snapshotTitle: string,
 *   snapshotCreatedAt: string,
 *   hasDrift: boolean,
 *   driftScore: number,
 *   driftSeverity: "none" | "low" | "medium" | "high" | "missing-snapshot",
 *   recommendedAction: string,
 *   driftItems: Array<{ field: string, label: string, before: string | number, current: string | number, delta: number }>,
 *   liveSummary: AgentExecutionResultTaskLedgerPayload["summary"] | null,
 *   snapshotSummary: { total: number, open: number, closed: number, visible: number, actionCount: number } | null,
 *   markdown: string
 * }} AgentExecutionResultTaskLedgerSnapshotDiffPayload
 * @typedef {{
 *   generatedAt: string,
 *   decision: "ready" | "review" | "hold",
 *   recommendedAction: string,
 *   reasons: AgentControlPlaneDecisionReason[],
 *   baselineHealth: "missing" | "healthy" | "changed" | "drifted" | "stale",
 *   baselineDriftSeverity: "none" | "low" | "medium" | "high" | "missing-baseline",
 *   baselineDriftRecommendedAction: string,
 *   releaseBuildGateDecision: "ready" | "review" | "hold" | "not-evaluated",
 *   releaseBuildGateRiskScore: number,
 *   releaseBuildGateReasonCount: number,
 *   releaseBuildGateActionCount: number,
 *   releaseBuildGate: ReleaseBuildGatePayload | null,
 *   releaseControlTaskCount: number,
 *   releaseControlOpenTaskCount: number,
 *   releaseControlClosedTaskCount: number,
 *   releaseControlTasks: PersistedTask[],
 *   agentControlPlaneDecisionTaskCount: number,
 *   agentControlPlaneDecisionOpenTaskCount: number,
 *   agentControlPlaneDecisionClosedTaskCount: number,
 *   agentControlPlaneDecisionTasks: PersistedTask[],
 *   activeRuns: number,
 *   staleActiveRuns: number,
 *   slaBreachedRuns: number,
 *   agentReadyProjects: number,
 *   agentReadinessItems: number,
 *   agentPolicyCheckpointCount: number,
 *   agentPolicyCheckpointApprovedCount: number,
 *   agentPolicyCheckpointDeferredCount: number,
 *   agentPolicyCheckpointDismissedCount: number,
 *   agentPolicyCheckpointNeedsReviewCount: number,
 *   agentPolicyCheckpointUnresolvedCount: number,
 *   agentPolicyExecutableCount: number,
 *   agentExecutionResultCheckpointCount: number,
 *   agentExecutionResultCheckpointApprovedCount: number,
 *   agentExecutionResultCheckpointDeferredCount: number,
 *   agentExecutionResultCheckpointDismissedCount: number,
 *   agentExecutionResultCheckpointNeedsReviewCount: number,
 *   agentExecutionResultCheckpointUnresolvedCount: number,
 *   agentExecutionResultCheckpointRequiredCount: number,
 *   agentExecutionResultBaselineBlockedCount: number,
 *   agentExecutionResultRequirements: AgentExecutionResultRequirements | null,
 *   agentExecutionResultTaskCount: number,
 *   agentExecutionResultOpenTaskCount: number,
 *   agentExecutionResultClosedTaskCount: number,
 *   agentExecutionResultTasks: PersistedTask[],
 *   dataSourcesGateDecision: "ready" | "review" | "hold" | "not-evaluated",
 *   dataSourcesReady: number,
 *   dataSourcesReview: number,
 *   dataSourcesBlocked: number,
 *   dataSourcesTokenLikely: number,
 *   dataSourcesAccessGate: DataSourcesAccessGatePayload | null,
 *   dataSourcesAccessReviewQueueCount: number,
 *   dataSourcesAccessReviewQueue: DataSourcesAccessReviewQueuePayload | null,
 *   dataSourcesAccessValidationMethodCount: number,
 *   dataSourcesAccessValidationSourceCount: number,
 *   dataSourcesAccessValidationReviewCount: number,
 *   dataSourcesAccessValidationBlockedCount: number,
 *   dataSourcesAccessValidationRunbook: DataSourcesAccessValidationRunbookPayload | null,
 *   dataSourcesAccessValidationEvidenceCount: number,
 *   dataSourcesAccessValidationEvidenceValidatedCount: number,
 *   dataSourcesAccessValidationEvidenceReviewCount: number,
 *   dataSourcesAccessValidationEvidenceBlockedCount: number,
 *   dataSourcesAccessValidationEvidenceCoverageCount: number,
 *   dataSourcesAccessValidationEvidenceCoverageCoveredCount: number,
 *   dataSourcesAccessValidationEvidenceCoverageReviewCount: number,
 *   dataSourcesAccessValidationEvidenceCoverageBlockedCount: number,
 *   dataSourcesAccessValidationEvidenceCoverageMissingCount: number,
 *   dataSourcesAccessValidationEvidenceCoverageHighPriorityCount: number,
 *   dataSourcesAccessValidationEvidenceCoveragePercent: number,
 *   dataSourcesAccessValidationEvidenceCoverage: DataSourcesAccessValidationEvidenceCoveragePayload | null,
 *   sourceAccessCheckpointCount: number,
 *   sourceAccessCheckpointApprovedCount: number,
 *   sourceAccessCheckpointDeferredCount: number,
 *   sourceAccessCheckpointDismissedCount: number,
 *   sourceAccessCheckpointNeedsReviewCount: number,
 *   sourceAccessCheckpointUnresolvedCount: number,
 *   sourceAccessCheckpointSources: number,
 *   sourceAccessCheckpointBySource: Array<{ source: string, total: number, approved: number, deferred: number, dismissed: number, needsReview: number, unresolved: number, latestAt: string }>,
 *   dataSourceAccessValidationEvidenceSnapshotCount: number,
 *   dataSourceAccessValidationEvidence: DataSourcesAccessValidationEvidenceRecord[],
 *   dataSourcesAccessTaskCount: number,
 *   dataSourcesAccessOpenTaskCount: number,
 *   dataSourcesAccessClosedTaskCount: number,
 *   dataSourcesAccessTasks: PersistedTask[],
 *   baselineStatus: GovernanceAgentControlPlaneBaselineStatus,
 *   agentExecutionMetrics: GovernanceAgentExecutionMetrics,
 *   summary: GovernancePayload["summary"],
 *   markdown: string
 * }} AgentControlPlaneDecisionPayload
 * @typedef {{
 *   addedCount: number,
 *   removedCount: number,
 *   changedCount: number,
 *   added: string[],
 *   removed: string[],
 *   changed: string[]
 * }} AgentControlPlaneSnapshotDriftSection
 * @typedef {{
 *   label: string,
 *   before: number,
 *   current: number,
 *   delta: number
 * }} AgentControlPlaneMetricDelta
 * @typedef {{
 *   generatedAt: string,
 *   snapshotId: string,
 *   snapshotTitle: string,
 *   snapshotCreatedAt: string,
 *   currentGeneratedAt: string,
 *   hasDrift: boolean,
 *   driftScore: number,
 *   driftSeverity: "none" | "low" | "medium" | "high" | "missing-baseline",
 *   recommendedAction: string,
 *   driftItems: Array<{ field: string, label: string, before: number, current: number, delta: number }>,
 *   metricDeltas: AgentControlPlaneMetricDelta[],
 *   readiness: AgentControlPlaneSnapshotDriftSection,
 *   executionRuns: AgentControlPlaneSnapshotDriftSection,
 *   slaLedger: AgentControlPlaneSnapshotDriftSection,
 *   workOrderSnapshots: AgentControlPlaneSnapshotDriftSection,
 *   governanceTaskUpdateLedgerSnapshots: AgentControlPlaneSnapshotDriftSection,
 *   slaLedgerSnapshots: AgentControlPlaneSnapshotDriftSection,
 *   markdown: string
 * }} AgentControlPlaneSnapshotDiffPayload
 * @typedef {{
 *   generatedAt: string,
 *   hasBaseline: boolean,
 *   baselineSnapshotId: string,
 *   snapshotTitle: string,
 *   snapshotCreatedAt: string,
 *   baselineAgeHours: number,
 *   baselineFreshness: "missing" | "fresh" | "stale",
 *   baselineFreshnessThresholdHours: number,
 *   health: "missing" | "healthy" | "changed" | "drifted" | "stale",
 *   recommendedAction: string,
 *   hasDrift: boolean,
 *   driftScore: number,
 *   driftSeverity: "none" | "low" | "medium" | "high" | "missing-baseline",
 *   driftRecommendedAction: string,
 *   driftItems: Array<{ field: string, label: string, before: number, current: number, delta: number }>,
 *   diff: AgentControlPlaneSnapshotDiffPayload | null,
 *   markdown: string
 * }} AgentControlPlaneBaselineStatusPayload
 * @typedef {{
 *   hasBaseline: boolean,
 *   snapshotId: string,
 *   title: string,
 *   createdAt: string,
 *   ageHours: number,
 *   freshness: "missing" | "fresh" | "stale",
 *   freshnessThresholdHours: number,
 *   hasDrift: boolean,
 *   driftScore: number,
 *   driftSeverity: "none" | "low" | "medium" | "high" | "missing-baseline",
 *   driftRecommendedAction: string,
 *   driftItems: Array<{ field: string, label: string, before: number, current: number, delta: number }>,
 *   health: "missing" | "healthy" | "changed" | "drifted" | "stale",
 *   recommendedAction: string,
 *   snapshotCount: number
 * }} GovernanceAgentControlPlaneBaselineStatus
 * @typedef {{
 *   id: string,
 *   type: string,
 *   label: string,
 *   value: string,
 *   path: string,
 *   url: string,
 *   resolvedPath: string,
 *   status: "reachable" | "registered" | "file" | "missing" | "unreachable" | "invalid-url",
 *   health: "ready" | "review" | "blocked",
 *   issue: string,
 *   access: DataSourceAccessProfile,
 *   sourceAccessCheckpoints: {
 *     total: number,
 *     approved: number,
 *     deferred: number,
 *     dismissed: number,
 *     needsReview: number,
 *     unresolved: number,
 *     sources: number,
 *     bySource: Array<{ source: string, total: number, approved: number, deferred: number, dismissed: number, needsReview: number, unresolved: number, latestAt: string }>,
 *     items: Array<{ id: string, batchId: string, title: string, source: string, status: string, itemCount: number, createdAt: string }>
 *   },
 *   addedAt: string,
 *   lastCheckedAt: string
 * }} DataSourceHealthRecord
 * @typedef {{
 *   accessLevel: string,
 *   accessMethod: string,
 *   requiresReview: boolean,
 *   passwordLikely: boolean,
 *   tokenLikely: boolean,
 *   certificateLikely: boolean,
 *   sshKeyLikely: boolean,
 *   privateRepoLikely: boolean,
 *   manualAccessLikely: boolean,
 *   localPathLikely: boolean,
 *   gitRemoteLikely: boolean,
 *   githubRemoteLikely: boolean,
 *   credentialHints: string[],
 *   notes: string[],
 *   secretPolicy: string
 * }} DataSourceAccessProfile
 * @typedef {{
 *   generatedAt: string,
 *   summary: {
 *     total: number,
 *     ready: number,
 *     review: number,
 *     blocked: number,
 *     local: number,
 *     remote: number,
 *     sourceAccessCheckpointCount: number,
 *     sourceAccessCheckpointApprovedCount: number,
 *     sourceAccessCheckpointDeferredCount: number,
 *     sourceAccessCheckpointDismissedCount: number,
 *     sourceAccessCheckpointNeedsReviewCount: number,
 *     sourceAccessCheckpointUnresolvedCount: number,
 *     sourceAccessCheckpointSources: number,
 *     sourceAccessCheckpointBySource: Array<{ source: string, total: number, approved: number, deferred: number, dismissed: number, needsReview: number, unresolved: number, latestAt: string }>,
 *     typeCounts: Record<string, number>
 *   },
 *   sources: DataSourceHealthRecord[],
 *   markdown: string
 * }} DataSourcesSummaryPayload
 * @typedef {{
 *   id: string,
 *   sourceId: string,
 *   label: string,
 *   provider: string,
 *   url: string,
 *   host: string,
 *   sourceHealth: string,
 *   sourceStatus: string,
 *   accessMethod: string,
 *   protectedLikely: boolean,
 *   secretPolicy: string,
 *   latestSmokeCheck: DeploymentSmokeCheckRecord | null
 * }} DeploymentHealthTarget
 * @typedef {{
 *   generatedAt: string,
 *   summary: {
 *     total: number,
 *     protectedLikely: number,
 *     targetChecked: number,
 *     checked: number,
 *     pass: number,
 *     fail: number,
 *     unknown: number,
 *     latestCheckedAt: string,
 *     latestStatus: string,
 *     providerCounts: Record<string, number>
 *   },
 *   targets: DeploymentHealthTarget[],
 *   recentSmokeChecks: DeploymentSmokeCheckRecord[],
 *   markdown: string
 * }} DeploymentHealthPayload
 * @typedef {{
 *   id: string,
 *   targetId: string,
 *   sourceId: string,
 *   label: string,
 *   provider: string,
 *   url: string,
 *   host: string,
 *   status: "pass" | "fail",
 *   ok: boolean,
 *   httpStatus: number,
 *   statusText: string,
 *   contentType: string,
 *   latencyMs: number,
 *   timeoutMs: number,
 *   error: string,
 *   checkedAt: string,
 *   secretPolicy: string,
 *   markdown: string
 * }} DeploymentSmokeCheckRecord
 * @typedef {{
 *   generatedAt: string,
 *   summary: {
 *     total: number,
 *     pass: number,
 *     fail: number,
 *     latestStatus: string,
 *     latestCheckedAt: string,
 *     latestTarget: string
 *   },
 *   smokeChecks: DeploymentSmokeCheckRecord[],
 *   markdown: string
 * }} DeploymentSmokeChecksPayload
 * @typedef {{
 *   id: string,
 *   title: string,
 *   status: "ready" | "review" | "hold",
 *   branch: string,
 *   commit: string,
 *   commitShort: string,
 *   commitMessage: string,
 *   dirty: boolean,
 *   changedFileCount: number,
 *   deploymentStatus: string,
 *   deploymentSmokeCheckCount: number,
 *   deploymentSmokeCheckPassCount: number,
 *   deploymentSmokeCheckFailCount: number,
 *   validationStatus: string,
 *   latestScanAt: string,
 *   notes: string,
 *   markdown: string,
 *   createdAt: string
 * }} ReleaseCheckpointRecord
 * @typedef {{
 *   generatedAt: string,
 *   summary: {
 *     status: "ready" | "review" | "hold",
 *     releaseCheckpointCount: number,
 *     deploymentSmokeCheckCount: number,
 *     deploymentSmokeCheckPassCount: number,
 *     deploymentSmokeCheckFailCount: number,
 *     latestScanAt: string,
 *     validationStatus: string
 *   },
 *   git: {
 *     available: boolean,
 *     branch: string,
 *     commit: string,
 *     commitShort: string,
 *     commitMessage: string,
 *     dirty: boolean,
 *     changedFileCount: number,
 *     changedFiles?: string[],
 *     error: string
 *   },
 *   latestSmokeCheck: DeploymentSmokeCheckRecord | null,
 *   checkpoints: ReleaseCheckpointRecord[],
 *   markdown: string
 * }} ReleaseSummaryPayload
 * @typedef {{
 *   field: string,
 *   label: string,
 *   before: string,
 *   current: string,
 *   severity: "low" | "medium" | "high"
 * }} ReleaseCheckpointDriftItem
 * @typedef {{
 *   generatedAt: string,
 *   hasSnapshot: boolean,
 *   snapshotId: string,
 *   snapshotTitle: string,
 *   snapshotCreatedAt: string,
 *   hasDrift: boolean,
 *   driftScore: number,
 *   driftSeverity: "none" | "low" | "medium" | "high" | "missing-checkpoint",
 *   recommendedAction: string,
 *   driftItems: ReleaseCheckpointDriftItem[],
 *   checkpoint: ReleaseCheckpointRecord | null,
 *   live: {
 *     status: "ready" | "review" | "hold",
 *     branch: string,
 *     commit: string,
 *     commitShort: string,
 *     commitMessage: string,
 *     dirty: boolean,
 *     changedFileCount: number,
 *     deploymentStatus: string,
 *     deploymentSmokeCheckCount: number,
 *     deploymentSmokeCheckPassCount: number,
 *     deploymentSmokeCheckFailCount: number,
 *     validationStatus: string,
 *     latestScanAt: string
 *   } | null,
 *   markdown: string
 * }} ReleaseCheckpointDriftPayload
 * @typedef {{
 *   code: string,
 *   label: string,
 *   message: string,
 *   severity: "low" | "medium" | "high"
 * }} ReleaseBuildGateReason
 * @typedef {{
 *   id: string,
 *   label: string,
 *   priority: "low" | "medium" | "high",
 *   status: "open" | "ready",
 *   description: string,
 *   commandHint: string
 * }} ReleaseBuildGateAction
 * @typedef {{
 *   generatedAt: string,
 *   decision: "ready" | "review" | "hold",
 *   riskScore: number,
 *   recommendedAction: string,
 *   reasons: ReleaseBuildGateReason[],
 *   actions: ReleaseBuildGateAction[],
 *   releaseSummary: ReleaseSummaryPayload,
 *   releaseCheckpointDrift: ReleaseCheckpointDriftPayload,
 *   markdown: string
 * }} ReleaseBuildGatePayload
 * @typedef {{
 *   id: string,
 *   title: string,
 *   status: string,
 *   priority: string,
 *   projectId: string,
 *   projectName: string,
 *   releaseBuildGateActionId: string,
 *   releaseBuildGateActionStatus: string,
 *   releaseBuildGateActionPriority: string,
 *   releaseBuildGateDecision: string,
 *   releaseBuildGateRiskScore: number,
 *   releaseBuildGateReasonCount: number,
 *   releaseBuildGateCommandHint: string,
 *   description: string,
 *   secretPolicy: string,
 *   createdAt: string,
 *   updatedAt: string
 * }} ReleaseTaskLedgerItem
 * @typedef {{
 *   generatedAt: string,
 *   status: "all" | "open" | "closed",
 *   limit: number,
 *   secretPolicy: string,
 *   summary: {
 *     total: number,
 *     open: number,
 *     closed: number,
 *     visible: number,
 *     high: number,
 *     medium: number,
 *     low: number,
 *     normal: number
 *   },
 *   items: ReleaseTaskLedgerItem[],
 *   markdown: string
 * }} ReleaseTaskLedgerPayload
 * @typedef {{
 *   id: string,
 *   title: string,
 *   statusFilter: "all" | "open" | "closed",
 *   limit: number,
 *   total: number,
 *   openCount: number,
 *   closedCount: number,
 *   visibleCount: number,
 *   secretPolicy: string,
 *   markdown: string,
 *   items: ReleaseTaskLedgerItem[],
 *   createdAt: string
 * }} PersistedReleaseTaskLedgerSnapshot
 * @typedef {{
 *   generatedAt: string,
 *   hasSnapshot: boolean,
 *   snapshotId: string,
 *   snapshotTitle: string,
 *   snapshotCreatedAt: string,
 *   hasDrift: boolean,
 *   driftScore: number,
 *   driftSeverity: "none" | "low" | "medium" | "high" | "missing-snapshot",
 *   recommendedAction: string,
 *   driftItems: Array<{ field: string, label: string, before: string | number, current: string | number, delta: number }>,
 *   liveSummary: ReleaseTaskLedgerPayload["summary"] | null,
 *   snapshotSummary: { total: number, open: number, closed: number, visible: number } | null,
 *   markdown: string
 * }} ReleaseTaskLedgerSnapshotDiffPayload
 * @typedef {{
 *   generatedAt: string,
 *   summary: {
 *     total: number,
 *     reviewRequired: number,
 *     tokenLikely: number,
 *     passwordLikely: number,
 *     certificateLikely: number,
 *     sshKeyLikely: number
 *   },
 *   sources: Array<{
 *     id: string,
 *     type: string,
 *     label: string,
 *     value: string,
 *     health: string,
 *     status: string,
 *     access: DataSourceAccessProfile
 *   }>,
 *   markdown: string
 * }} DataSourcesAccessRequirementsPayload
 * @typedef {{
 *   id: string,
 *   label: string,
 *   type: string,
 *   locator: string,
 *   health: string,
 *   status: string,
 *   accessMethod: string,
 *   accessLevel: string,
 *   requiresReview: boolean,
 *   localPathLikely: boolean,
 *   gitRemoteLikely: boolean,
 *   githubRemoteLikely: boolean,
 *   privateRepoLikely: boolean,
 *   tokenLikely: boolean,
 *   passwordLikely: boolean,
 *   certificateLikely: boolean,
 *   sshKeyLikely: boolean,
 *   manualAccessLikely: boolean,
 *   credentialHints: string[],
 *   notes: string[],
 *   secretPolicy: string
 * }} DataSourcesAccessMethodRegistrySource
 * @typedef {{
 *   accessMethod: string,
 *   title: string,
 *   category: string,
 *   sourceCount: number,
 *   ready: number,
 *   review: number,
 *   blocked: number,
 *   reviewRequired: number,
 *   localPathSources: number,
 *   gitRemoteSources: number,
 *   githubRemoteSources: number,
 *   privateRepoLikely: number,
 *   tokenLikely: number,
 *   passwordLikely: number,
 *   certificateLikely: number,
 *   sshKeyLikely: number,
 *   manualAccessLikely: number,
 *   commandHints: string[],
 *   externalSetup: string,
 *   secretHandling: string,
 *   sources: DataSourcesAccessMethodRegistrySource[]
 * }} DataSourcesAccessMethodRegistryMethod
 * @typedef {{
 *   generatedAt: string,
 *   summary: {
 *     totalSources: number,
 *     totalMethods: number,
 *     readySources: number,
 *     reviewSources: number,
 *     blockedSources: number,
 *     reviewRequired: number,
 *     localPathSources: number,
 *     gitRemoteSources: number,
 *     githubRemoteSources: number,
 *     privateRepoLikely: number,
 *     tokenLikely: number,
 *     passwordLikely: number,
 *     certificateLikely: number,
 *     sshKeyLikely: number,
 *     manualAccessLikely: number
 *   },
 *   secretPolicy: string,
 *   methods: DataSourcesAccessMethodRegistryMethod[],
 *   sources: DataSourcesAccessMethodRegistrySource[],
 *   requirements: DataSourcesAccessRequirementsPayload,
 *   matrix: DataSourcesAccessMatrixPayload,
 *   runbook: DataSourcesAccessValidationRunbookPayload,
 *   markdown: string
 * }} DataSourcesAccessMethodRegistryPayload
 * @typedef {{
 *   id: string,
 *   sourceId: string,
 *   label: string,
 *   type: string,
 *   locator: string,
 *   accessMethod: string,
 *   category: string,
 *   status: "ready" | "pending" | "blocked",
 *   stage: "validated" | "record-validation-evidence" | "external-access-review" | "blocked",
 *   priority: "high" | "medium" | "low",
 *   externalAccessRequired: boolean,
 *   blockerTypes: string[],
 *   latestEvidenceStatus: string,
 *   latestEvidenceAt: string,
 *   coverageStatus: string,
 *   action: string,
 *   commandHints: string[],
 *   secretPolicy: string
 * }} DataSourcesAccessValidationWorkflowItem
 * @typedef {{
 *   generatedAt: string,
 *   summary: {
 *     total: number,
 *     ready: number,
 *     pending: number,
 *     blocked: number,
 *     missingEvidence: number,
 *     externalAccessRequired: number,
 *     tokenRequired: number,
 *     passwordRequired: number,
 *     certificateRequired: number,
 *     sshRequired: number,
 *     manualRequired: number
 *   },
 *   secretPolicy: string,
 *   items: DataSourcesAccessValidationWorkflowItem[],
 *   registry: DataSourcesAccessMethodRegistryPayload,
 *   coverage: DataSourcesAccessValidationEvidenceCoveragePayload,
 *   markdown: string
 * }} DataSourcesAccessValidationWorkflowPayload
 * @typedef {{
 *   id: string,
 *   title: string,
 *   total: number,
 *   readyCount: number,
 *   pendingCount: number,
 *   blockedCount: number,
 *   missingEvidenceCount: number,
 *   externalAccessRequiredCount: number,
 *   tokenRequiredCount: number,
 *   passwordRequiredCount: number,
 *   certificateRequiredCount: number,
 *   sshRequiredCount: number,
 *   manualRequiredCount: number,
 *   secretPolicy: string,
 *   markdown: string,
 *   items: DataSourcesAccessValidationWorkflowItem[],
 *   createdAt: string
 * }} PersistedDataSourcesAccessValidationWorkflowSnapshot
 * @typedef {{
 *   generatedAt: string,
 *   hasSnapshot: boolean,
 *   snapshotId: string,
 *   snapshotTitle: string,
 *   snapshotCreatedAt: string,
 *   hasDrift: boolean,
 *   driftScore: number,
 *   driftSeverity: "none" | "low" | "medium" | "high" | "missing-snapshot",
 *   recommendedAction: string,
 *   driftItems: Array<{ field: string, label: string, before: string | number, current: string | number, delta: number }>,
 *   liveSummary: DataSourcesAccessValidationWorkflowPayload["summary"] | null,
 *   snapshotSummary: { total: number, ready: number, pending: number, blocked: number, missingEvidence: number, externalAccessRequired: number, tokenRequired: number, passwordRequired: number, certificateRequired: number, sshRequired: number, manualRequired: number } | null,
 *   markdown: string
 * }} DataSourcesAccessValidationWorkflowSnapshotDiffPayload
 * @typedef {{
 *   generatedAt: string,
 *   summary: {
 *     total: number,
 *     ready: number,
 *     review: number,
 *     blocked: number
 *   },
 *   items: Array<{
 *     id: string,
 *     sourceId: string,
 *     label: string,
 *     type: string,
 *     value: string,
 *     sourceHealth: string,
 *     sourceStatus: string,
 *     status: "ready" | "review" | "blocked",
 *     accessMethod: string,
 *     action: string,
 *     validation: string,
 *     credentialHint: string,
 *     secretPolicy: string
 *   }>,
 *   markdown: string
 * }} DataSourcesAccessChecklistPayload
 * @typedef {{
 *   accessMethod: string,
 *   title: string,
 *   steps: string[],
 *   commandHints: string[],
 *   evidence: string,
 *   sources: Array<{
 *     sourceId: string,
 *     label: string,
 *     type: string,
 *     status: string,
 *     sourceHealth: string,
 *     sourceStatus: string,
 *     credentialHint: string,
 *     secretPolicy: string
 *   }>
 * }} DataSourcesAccessValidationRunbookMethod
 * @typedef {{
 *   generatedAt: string,
 *   summary: {
 *     methodCount: number,
 *     sourceCount: number,
 *     ready: number,
 *     review: number,
 *     blocked: number
 *   },
 *   methods: DataSourcesAccessValidationRunbookMethod[],
 *   checklist: DataSourcesAccessChecklistPayload,
 *   markdown: string
 * }} DataSourcesAccessValidationRunbookPayload
 * @typedef {{
 *   id: string,
 *   sourceId: string,
 *   sourceLabel: string,
 *   sourceType: string,
 *   accessMethod: string,
 *   status: "validated" | "review" | "blocked",
 *   evidence: string,
 *   commandHint: string,
 *   checkedAt: string,
 *   createdAt: string,
 *   updatedAt: string,
 *   secretPolicy: string
 * }} DataSourcesAccessValidationEvidenceRecord
 * @typedef {{
 *   generatedAt: string,
 *   status: "all" | "validated" | "review" | "blocked",
 *   sourceId: string,
 *   accessMethod: string,
 *   limit: number,
 *   total: number,
 *   summary: {
 *     total: number,
 *     validated: number,
 *     review: number,
 *     blocked: number,
 *     methodCount: number,
 *     sourceCount: number
 *   },
 *   secretPolicy: string,
 *   items: DataSourcesAccessValidationEvidenceRecord[],
 *   markdown: string
 * }} DataSourcesAccessValidationEvidencePayload
 * @typedef {{
 *   total: number,
 *   approved: number,
 *   deferred: number,
 *   dismissed: number,
 *   needsReview: number,
 *   unresolved: number,
 *   sources: number,
 *   bySource: Array<{ source: string, total: number, approved: number, deferred: number, dismissed: number, needsReview: number, unresolved: number, latestAt: string }>,
 *   items: Array<{ id: string, batchId: string, title: string, source: string, status: string, itemCount: number, createdAt: string }>
 * }} SourceAccessCheckpointDrilldown
 * @typedef {{
 *   id: string,
 *   sourceId: string,
 *   label: string,
 *   type: string,
 *   status: string,
 *   sourceHealth: string,
 *   sourceStatus: string,
 *   accessMethod: string,
 *   coverageStatus: "covered" | "review" | "blocked" | "missing",
 *   priority: "high" | "medium" | "low",
 *   action: string,
 *   latestEvidenceId: string,
 *   latestEvidenceStatus: string,
 *   latestEvidenceAt: string,
 *   latestEvidenceSummary: string,
 *   sourceAccessCheckpoints: SourceAccessCheckpointDrilldown,
 *   secretPolicy: string
 * }} DataSourcesAccessValidationEvidenceCoverageItem
 * @typedef {{
 *   generatedAt: string,
 *   summary: {
 *     sourceCount: number,
 *     covered: number,
 *     review: number,
 *     blocked: number,
 *     missing: number,
 *     highPriority: number,
 *     mediumPriority: number,
 *     methodCount: number,
 *     coveragePercent: number,
 *     checkpointCount: number,
 *     checkpointApproved: number,
 *     checkpointDeferred: number,
 *     checkpointDismissed: number,
 *     checkpointNeedsReview: number,
 *     checkpointUnresolved: number,
 *     checkpointSources: number,
 *     checkpointBySource: Array<{ source: string, total: number, approved: number, deferred: number, dismissed: number, needsReview: number, unresolved: number, latestAt: string }>
 *   },
 *   secretPolicy: string,
 *   items: DataSourcesAccessValidationEvidenceCoverageItem[],
 *   runbook: DataSourcesAccessValidationRunbookPayload,
 *   markdown: string
 * }} DataSourcesAccessValidationEvidenceCoveragePayload
 * @typedef {{
 *   id: string,
 *   title: string,
 *   statusFilter: "all" | "validated" | "review" | "blocked",
 *   sourceId: string,
 *   accessMethod: string,
 *   limit: number,
 *   total: number,
 *   validatedCount: number,
 *   reviewCount: number,
 *   blockedCount: number,
 *   methodCount: number,
 *   sourceCount: number,
 *   secretPolicy: string,
 *   markdown: string,
 *   items: DataSourcesAccessValidationEvidenceRecord[],
 *   createdAt: string
 * }} PersistedDataSourcesAccessValidationEvidenceSnapshot
 * @typedef {{
 *   generatedAt: string,
 *   hasSnapshot: boolean,
 *   snapshotId: string,
 *   snapshotTitle: string,
 *   snapshotCreatedAt: string,
 *   hasDrift: boolean,
 *   driftScore: number,
 *   driftSeverity: "none" | "low" | "medium" | "high" | "missing-snapshot",
 *   recommendedAction: string,
 *   driftItems: Array<{ field: string, label: string, before: string | number, current: string | number, delta: number }>,
 *   liveSummary: DataSourcesAccessValidationEvidencePayload["summary"] | null,
 *   snapshotSummary: { total: number, validated: number, review: number, blocked: number, methodCount: number, sourceCount: number } | null,
 *   markdown: string
 * }} DataSourcesAccessValidationEvidenceSnapshotDiffPayload
 * @typedef {{
 *   accessMethod: string,
 *   total: number,
 *   reviewRequired: number,
 *   tokenLikely: number,
 *   passwordLikely: number,
 *   certificateLikely: number,
 *   sshKeyLikely: number,
 *   sources: Array<{
 *     id: string,
 *     label: string,
 *     type: string,
 *     health: string,
 *     status: string,
 *     accessLevel: string,
 *     requiresReview: boolean,
 *     credentialHints: string[],
 *     notes: string[]
 *   }>
 * }} DataSourcesAccessMatrixMethod
 * @typedef {{
 *   generatedAt: string,
 *   summary: {
 *     total: number,
 *     methodCount: number,
 *     reviewRequired: number,
 *     tokenLikely: number,
 *     passwordLikely: number,
 *     certificateLikely: number,
 *     sshKeyLikely: number
 *   },
 *   methods: DataSourcesAccessMatrixMethod[],
 *   requirements: DataSourcesAccessRequirementsPayload,
 *   markdown: string
 * }} DataSourcesAccessMatrixPayload
 * @typedef {{
 *   id: string,
 *   sourceId: string,
 *   label: string,
 *   type: string,
 *   value: string,
 *   title: string,
 *   status: "review" | "blocked",
 *   priority: "high" | "medium" | "normal",
 *   accessMethod: string,
 *   sourceHealth: string,
 *   sourceStatus: string,
 *   action: string,
 *   validation: string,
 *   credentialHint: string,
 *   sourceAccessCheckpoints: SourceAccessCheckpointDrilldown,
 *   secretPolicy: string
 * }} DataSourcesAccessReviewQueueItem
 * @typedef {{
 *   generatedAt: string,
 *   summary: {
 *     total: number,
 *     review: number,
 *     blocked: number,
 *     high: number,
 *     medium: number,
 *     normal: number,
 *     methodCount: number,
 *     tokenLikely: number,
 *     passwordLikely: number,
 *     certificateLikely: number,
 *     sshKeyLikely: number,
 *     checkpointCount: number,
 *     checkpointApproved: number,
 *     checkpointDeferred: number,
 *     checkpointDismissed: number,
 *     checkpointNeedsReview: number,
 *     checkpointUnresolved: number,
 *     checkpointSources: number,
 *     checkpointBySource: Array<{ source: string, total: number, approved: number, deferred: number, dismissed: number, needsReview: number, unresolved: number, latestAt: string }>
 *   },
 *   items: DataSourcesAccessReviewQueueItem[],
 *   checklist: DataSourcesAccessChecklistPayload,
 *   matrix: DataSourcesAccessMatrixPayload,
 *   markdown: string
 * }} DataSourcesAccessReviewQueuePayload
 * @typedef {{
 *   id: string,
 *   title: string,
 *   status: string,
 *   priority: string,
 *   sourceAccessReviewId: string,
 *   sourceAccessValidationEvidenceCoverageId: string,
 *   sourceAccessValidationWorkflowId: string,
 *   sourceId: string,
 *   sourceLabel: string,
 *   sourceType: string,
 *   sourceValue: string,
 *   accessMethod: string,
 *   workflowStage: string,
 *   workflowStatus: string,
 *   blockerTypes: string[],
 *   coverageStatus: string,
 *   latestEvidenceStatus: string,
 *   latestEvidenceId: string,
 *   latestEvidenceAt: string,
 *   lastSourceAccessValidationEvidenceId: string,
 *   lastSourceAccessValidationEvidenceStatus: string,
 *   lastSourceAccessValidationEvidenceAt: string,
 *   secretPolicy: string,
 *   createdAt: string,
 *   updatedAt: string
 * }} DataSourcesAccessTaskLedgerItem
 * @typedef {{
 *   generatedAt: string,
 *   status: "all" | "open" | "closed",
 *   limit: number,
 *   secretPolicy: string,
 *   summary: {
 *     total: number,
 *     open: number,
 *     closed: number,
 *     visible: number,
 *     high: number,
 *     medium: number,
 *     low: number,
 *     normal: number,
 *     methodCount: number,
 *     accessMethods: Record<string, number>
 *   },
 *   items: DataSourcesAccessTaskLedgerItem[],
 *   markdown: string
 * }} DataSourcesAccessTaskLedgerPayload
 * @typedef {{
 *   id: string,
 *   title: string,
 *   statusFilter: "all" | "open" | "closed",
 *   limit: number,
 *   total: number,
 *   openCount: number,
 *   closedCount: number,
 *   visibleCount: number,
 *   secretPolicy: string,
 *   markdown: string,
 *   items: DataSourcesAccessTaskLedgerItem[],
 *   createdAt: string
 * }} PersistedDataSourcesAccessTaskLedgerSnapshot
 * @typedef {{
 *   generatedAt: string,
 *   hasSnapshot: boolean,
 *   snapshotId: string,
 *   snapshotTitle: string,
 *   snapshotCreatedAt: string,
 *   hasDrift: boolean,
 *   driftScore: number,
 *   driftSeverity: "none" | "low" | "medium" | "high" | "missing-snapshot",
 *   recommendedAction: string,
 *   driftItems: Array<{ category?: string, field: string, label: string, before: string | number, current: string | number, delta: number }>,
 *   liveSummary: DataSourcesAccessTaskLedgerPayload["summary"] | null,
 *   snapshotSummary: { total: number, open: number, closed: number, visible: number } | null,
 *   liveWorkflowTaskSummary?: { total: number, open: number, closed: number, blocked: number, ready: number, pending: number } | null,
 *   snapshotWorkflowTaskSummary?: { total: number, open: number, closed: number, blocked: number, ready: number, pending: number } | null,
 *   markdown: string
 * }} DataSourcesAccessTaskLedgerSnapshotDiffPayload
 * @typedef {{
 *   generatedAt: string,
 *   decision: "ready" | "review" | "hold",
 *   recommendedAction: string,
 *   reasons: Array<{ severity: "review" | "hold", code: string, message: string }>,
 *   total: number,
 *   ready: number,
 *   review: number,
 *   blocked: number,
 *   tokenLikely: number,
 *   passwordLikely: number,
 *   certificateLikely: number,
 *   sshKeyLikely: number,
 *   checklist: DataSourcesAccessChecklistPayload,
 *   accessRequirements: DataSourcesAccessRequirementsPayload,
 *   markdown: string
 * }} DataSourcesAccessGatePayload
 * @typedef {{
 *   id: string,
 *   title: string,
 *   total: number,
 *   ready: number,
 *   review: number,
 *   blocked: number,
 *   local: number,
 *   remote: number,
 *   typeCounts: Record<string, number>,
 *   markdown: string,
 *   sources: DataSourceHealthRecord[],
 *   payload: DataSourcesSummaryPayload,
 *   createdAt: string
 * }} PersistedDataSourcesSummarySnapshot
 * @typedef {{
 *   generatedAt: string,
 *   hasSnapshot: boolean,
 *   snapshotId: string,
 *   snapshotTitle: string,
 *   snapshotCreatedAt: string,
 *   hasDrift: boolean,
 *   driftScore: number,
 *   driftSeverity: "none" | "low" | "medium" | "high" | "missing-snapshot",
 *   recommendedAction: string,
 *   driftItems: Array<{ field: string, label: string, before: string | number, current: string | number, delta: number }>,
 *   liveSummary: DataSourcesSummaryPayload["summary"] | null,
 *   snapshotSummary: DataSourcesSummaryPayload["summary"] | Record<string, number> | null,
 *   markdown: string
 * }} DataSourcesSummarySnapshotDiffPayload
 * @typedef {"api" | "file" | "embedded" | "unavailable"} InventorySource
 * @typedef {"idle" | "loading" | "ready" | "empty" | "error"} PanelLoadStatus
 * @typedef {{
 *   status: PanelLoadStatus,
 *   lastLoadedAt?: string,
 *   itemCount?: number,
 *   message?: string
 * }} PanelRuntimeState
 * @typedef {{
 *   inventorySource: InventorySource,
 *   lastLoadedAt?: string,
 *   snapshotGeneratedAt?: string,
 *   loadError?: string,
 *   panels: {
 *     findings: PanelRuntimeState,
 *     trends: PanelRuntimeState,
 *     sources: PanelRuntimeState,
 *     governance: PanelRuntimeState
 *   }
 * }} DashboardRuntimeState
 * @typedef {{
 *   search: string,
 *   zone: string,
 *   category: string,
 *   sortKey: string,
 *   sortDir: "asc" | "desc",
 *   showArchived: boolean,
 *   view: "grid" | "table" | "graph" | "findings" | "trends" | "sources" | "governance"
 * }} DashboardState
 */

export {};
